url: "https://hoylandstpetersfc.lotterybingo.club"
baseurl: "/"

name: "Hoyland St Peters FC"
strapline: "Together, we succeed."
about: "This Lottery Bingo game supports the fundraising efforts of our club, allowing us to provide excellent training sessions and engaging social events for our players."
logo: "/assets/images/logo--hspfc.png"

email: "hoylandsp@outlook.com"
facebook: "hoylandstpetersfc"
website: "https://www.hoylandstpetersfc.co.uk/"
address: "13 Armroyd Ln, Elsecar, Barnsley S74 8ES"
map-coords: "53.49459367844664, -1.424442542330539"
join: "https://forms.gle/wHAqiLAEjuJ8rLn79"